### ISSUE TITLE
colander.drop not working for sequences and tuples

### ISSUE THREAD

**Issue by pallix** [Pylons/colander#224]
Using ```missing=colander.drop``` does not work when deserializing a sequence or a tuple. Instead of dropping the value colander uses literalarly ```drop``` as a value. I'm using colander 1.0.

```
import colander
 

class Friends(colander.SequenceSchema):
    name = colander.SchemaNode(colander.String(), missing=colander.drop)
 
 
Friends().deserialize(['tom', None])
 
>>> ['tom', <colander._drop at 0x7efee92fd588>]
 
class Toy(colander.TupleSchema):
    name = colander.SchemaNode(colander.String())
    price = colander.SchemaNode(colander.String(), missing=colander.drop)
 
 
Toy().deserialize(('lego', None))
 
>>> ('lego', <colander._drop at 0x7efee92fd588>)
```

**Comment by tisdall** [comment]
@mmerickel - I think this can be closed now than #225 has been merged in.

There's no way to support `drop` in a tuple since the length is fixed and the order is what's used to determine how the value is interpreted.  The best you could do is drop values off the end of the tuple since dropping values in the middle would change how subsequent values were interpreted.
