### ISSUE TITLE
preparer cannot call under subclassed SchemaNode

### ISSUE THREAD

**Issue by gjo** [Pylons/colander#256]
`colander.interfaces.Preparer` says preparer has one argument.
However, when a SchemaNode is subclass-ed, `preparer.__call__(value)` requires two arguments (`self` and `value`) and raises exception.

```python
import colander as c

def global_preparer(value):
    return 'global_prepared:' + value


class Schema1(c.Schema):
    node = c.SchemaNode(typ=c.Str(), preparer=global_preparer)


schema1 = Schema1().bind()
deserialized = schema1.deserialize({'node': 'test'})
print('Schema1:', deserialized)
# printed
# Schema1: {'node': 'global_prepared:test'}

class Node(c.SchemaNode):
    schema_type = c.Str
    preparer = global_preparer


class Schema2(c.Schema):
    node = Node()


schema2 = Schema2().bind()
deserialized = schema2.deserialize({'node': 'test'})
# exceptioned
# TypeError: global_preparer() takes 1 positional argument but 2 were given
```

**Comment by mmerickel** [comment]
Yes, the preparer has one argument passed. However if you make the preparer a method then you must also accept the implicit `self` argument. This is not a bug or anything, just basic Python. If you do not want to change the preparer because it doesn't need access to `self` then you can make it a static method. In your last example you could do `preparer = staticmethod(global_preparer)` which will strip the `self` before calling your function.
